#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
<<<<<<< HEAD
# Generated by Vivado on Mon Oct 28 12:07:20 CET 2024
=======
# Generated by Vivado on Mon Oct 28 12:18:23 CET 2024
>>>>>>> 346f26ebc544d91ba663b6868c2a78304c7c9ace
# SW Build 5164865 on Thu Sep  5 14:36:28 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LSTM_ACCELERATOR_test_behav xil_defaultlib.LSTM_ACCELERATOR_test -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LSTM_ACCELERATOR_test_behav xil_defaultlib.LSTM_ACCELERATOR_test -log elaborate.log

